version: "2"

linters:
  default: fast

  enable:
    - cyclop
  
  disable:
    - depguard
    - mnd
    - testpackage
    - gocyclo
    - tagalign
  
  settings:
    cyclop:
      # TODO decrease this to 10
      max-complexity: 15
  
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - funlen
          - lll
